# Generated by Django 4.0.1 on 2022-01-17 19:25

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('inventory', '0002_inventory_manufacturer_inventory_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
